
spring.cassandra.keyspace-name=taco_cloud

spring.cassandra.contact-points=localhost

spring.cassandra.port=9042

spring.cassandra.local-datacenter=datacenter1

spring.cassandra.schema-action=recreate_drop_unused


